blank_issues_enabled: false
contact_links:
  - name: Questions and Discussions
    url: https://github.com/RazinShafayet2007/typedjs/discussions
    about: Ask questions or start a discussion about TypedJS
